export const PROJECTS = [
  {
    index: "01",
    slug: "verisight",
    image: "/assets/project-verisight.png",
    title: "VeriSight V1",
    subtitle: "Image Authenticity Verification",
    desc: "Multi-layer AI system running CNN, ViT, GAN, and OCR models in parallel via async FastAPI orchestration — built to stop fraud at scale.",
    problem:
      "High-volume applications had no reliable method to verify image authenticity, leaving fraud undetected.",
    solution:
      "A multi-layer AI system that fuses CNN, ViT, GAN, and OCR predictions in parallel via async FastAPI orchestration, delivering a single confidence verdict.",
    impact: 45,
    impactLabel: "fraud detection improvement",
    tags: ["Python", "FastAPI", "PyTorch", "CNN", "ViT", "GAN", "OCR"],
    url: "https://github.com/NYN-05/verisight",
    status: "Production",
    featured: true,
    duration: "6 weeks",
    role: "Solo — design, ML, backend",
  },
  {
    index: "02",
    slug: "preventive-movement-intelligence",
    image: "/assets/project-pmi.png",
    title: "Preventive Movement Intelligence",
    subtitle: "Real-Time Posture Analytics",
    desc: "MoveNet-based pose inference with FastAPI for real-time landmark extraction and injury risk scoring during exercise.",
    problem: "Athletes and fitness enthusiasts lack real-time injury risk assessment while training.",
    solution:
      "MoveNet pose inference with FastAPI extracts landmarks in real time and computes a dynamic injury-risk score.",
    impact: 72,
    impactLabel: "injury risk reduction",
    tags: ["Python", "FastAPI", "TensorFlow", "MoveNet", "Pose Estimation"],
    url: "https://github.com/NYN-05/verisight",
    status: "BIRAC Prototype",
    featured: false,
    duration: "5 weeks",
    role: "Solo — research, model, API",
  },
  {
    index: "03",
    slug: "edushield",
    image: "/assets/project-edushield.png",
    title: "EduShield",
    subtitle: "Phishing Email Detection",
    desc: "TF-IDF + Logistic Regression & SVM for real-time email classification with explainable outputs.",
    problem: "Rising phishing attacks in educational institutions targeting credentials and personal data.",
    solution:
      "TF-IDF vectorization with logistic regression and SVM ensembles, tuned for explainable real-time classification.",
    impact: 88,
    impactLabel: "detection accuracy",
    tags: ["Python", "scikit-learn", "NLP", "TF-IDF", "SVM"],
    url: "https://github.com/NYN-05/verisight",
    status: "Production",
    featured: false,
    duration: "4 weeks",
    role: "Solo — research, model, API",
  },
  {
    index: "04",
    slug: "scalable-ml-backend",
    image: "/assets/project-backend.png",
    title: "Scalable ML Backend",
    subtitle: "Production Infrastructure",
    desc: "FastAPI with async processing, Redis caching, CI/CD pipelines, and Docker containerization for ML services.",
    problem: "ML models need robust backend infrastructure to reach production and scale under real load.",
    solution:
      "Async FastAPI services with Redis caching, containerized deploys, and CI/CD pipelines cut latency and operational overhead.",
    impact: 60,
    impactLabel: "API latency reduction",
    tags: ["FastAPI", "Redis", "Docker", "CI/CD", "PostgreSQL"],
    url: "https://github.com/NYN-05/verisight",
    status: "Production",
    featured: false,
    duration: "3 weeks",
    role: "Solo — architecture, infrastructure",
  },
];