export const FEATURED_SLUGS = [
  "campus-map",
  "food-recognition",
  "terminal-media-player",
];

export function getFeaturedProjects() {
  return FEATURED_SLUGS.map((slug) => PROJECTS.find((p) => p.slug === slug)).filter(Boolean);
}

export const PROJECTS = [
  {
    index: "01",
    slug: "campus-map",
    image: "/assets/project-map.png",
    title: "Real-Time Campus Map",
    subtitle: "Web App · Navigation",
    category: "web-app",
    categoryLabel: "Web App",
    categoryBadges: ["[WEB]", "[REACT]", "[EXPRESS]", "[SOCKET.IO]"],
    desc: "An interactive map designed to navigate campus with live updates and smart search.",
    problem:
      "Students and visitors struggled to navigate a large campus with paper maps and static signage, facing wasted time and missed locations.",
    solution:
      "Built an interactive web map with live building indicators, smart search for rooms and facilities, and a clean mobile-first interface.",
    engineeringChallenges:
      "Rendering smooth pan/zoom on low-end devices; keeping map data in sync with live updates without rebuilding the whole scene; designing an intuitive search across hundreds of locations.",
    architecture: {
      flow: "React Map View → Location Index → Search Index → Live Updates Feed",
      engineeringCapabilities: ["REST APIs", "State Management", "Responsive UI", "Search", "Caching"],
      mlCapabilities: ["Geospatial Indexing"],
      infrastructure: ["Vite", "Netlify", "CI/CD"],
    },
    impact: 10,
    impactLabel: "builds shipped",
    summary: "Interactive campus navigation with live updates and smart search.",
    tags: ["React", "JavaScript", "HTML", "CSS", "Express", "Socket.IO"],
    stackShort: ["React", "JavaScript", "Express"],
    url: "https://github.com/NYN-05",
    demoUrl: "https://github.com/NYN-05",
    status: "Live",
    featured: true,
    homepageFeatured: true,
    duration: "6 weeks",
    role: "Solo — Full stack, UI, Data",
  },
  {
    index: "02",
    slug: "food-recognition",
    image: "/assets/project-food.png",
    title: "Food Recognition System",
    subtitle: "ML / AI · Deep Learning",
    category: "ml-ai",
    categoryLabel: "ML / AI",
    categoryBadges: ["[PYTHON]", "[TENSORFLOW]", "[CNN]"],
    desc: "A deep-learning system designed to identify food items from images with high accuracy.",
    problem:
      "Tracking nutrition manually is tedious. Users needed a fast way to identify food from a photo to log meals automatically.",
    solution:
      "Trained a CNN classifier on a broad food dataset and exposed it through a clean web interface that labels dishes from a single image.",
    engineeringChallenges:
      "Dealing with class imbalance across cuisines; keeping inference fast enough for a pleasant upload-to-result experience; building a dataset pipeline from public sources.",
    architecture: {
      flow: "Image Upload → Preprocessing → CNN Inference → Label + Confidence",
      engineeringCapabilities: ["REST APIs", "Preprocessing", "Evaluation"],
      mlCapabilities: ["Data Pipeline", "Model Training", "Augmentation", "Inference"],
      infrastructure: ["Python", "Flask", "Cloud"],
    },
    impact: 92,
    impactLabel: "classification accuracy",
    summary: "A deep-learning CNN that identifies food items from images with high accuracy.",
    tags: ["Python", "TensorFlow", "CNN", "OpenCV", "Flask", "Pandas"],
    stackShort: ["Python", "TensorFlow", "CNN"],
    url: "https://github.com/NYN-05",
    demoUrl: "https://github.com/NYN-05",
    status: "Prototype",
    featured: true,
    homepageFeatured: true,
    duration: "8 weeks",
    role: "Solo — Data, Model, API",
  },
  {
    index: "03",
    slug: "terminal-media-player",
    image: "/assets/project-terminal.png",
    title: "Terminal Media Player",
    subtitle: "Developer Tool · CLI",
    category: "dev-tool",
    categoryLabel: "Developer Tool",
    categoryBadges: ["[C++]", "[LINUX]", "[CLI]"],
    desc: "A lightweight terminal-based media player with a clean interactive interface.",
    problem:
      "Heavy media players waste memory on low-spec machines. A minimal CLI player could play audio from the terminal with almost no footprint.",
    solution:
      "Built a terminal media player in C++ that renders a clean interactive interface, supports common audio formats, and stays light on resources.",
    engineeringChallenges:
      "Parsing media streams without third-party heavyweight libraries; rendering real-time progress UI in the terminal; handling keyboard-driven controls consistently.",
    architecture: {
      flow: "Playlist → Decoder → Terminal UI → Keyboard Controls",
      engineeringCapabilities: ["Systems Programming", "I/O", "Event Loop"],
      mlCapabilities: [],
      infrastructure: ["CMake", "Linux", "Git"],
    },
    impact: 0,
    impactLabel: "dependencies, runs anywhere",
    summary: "A lightweight terminal media player with a clean interactive interface.",
    tags: ["C++", "Java", "Linux", "CLI", "CMake"],
    stackShort: ["C++", "Java", "Linux"],
    url: "https://github.com/NYN-05",
    demoUrl: "https://github.com/NYN-05",
    status: "Open Source",
    featured: true,
    homepageFeatured: true,
    duration: "4 weeks",
    role: "Solo — Systems, UI, Decoder",
  },
  {
    index: "04",
    slug: "verisight",
    image: "/assets/project-verisight.png",
    title: "VeriSight",
    subtitle: "Intelligent Image Authenticity Verification Platform",
    category: "ml-ai",
    categoryLabel: "ML / Backend",
    categoryBadges: ["[BACKEND]", "[SYSTEMS]", "[ML]", "[FASTAPI]", "[PYTORCH]"],
    desc: "An end-to-end intelligent system designed to solve high-volume digital tampering using a combination of backend engineering, asynchronous pipeline orchestration, and multi-model machine learning inference.",
    problem:
      "High-volume digital workflows lacked an automated, tamper-proof system to detect synthetic forgeries and metadata alterations under sub-second latency constraints.",
    solution:
      "Architected an asynchronous pipeline orchestrating deep learning models in parallel with strict timeout policies, confidence fusion, and structured audit logs.",
    engineeringChallenges:
      "Preventing head-of-line blocking during multi-model parallel inference; maintaining sub-500ms p95 latency under concurrent traffic; designing clean REST contracts with full auditability.",
    architecture: {
      flow: "Frontend (React) → API Gateway (FastAPI) → Application Layer (AsyncIO) → Database (PostgreSQL + Redis) → Parallel ML Inference (CNN + ViT + GAN + OCR)",
      engineeringCapabilities: [
        "REST APIs",
        "Authentication",
        "Database Design",
        "Async Processing",
        "Testing",
        "Deployment",
      ],
      mlCapabilities: [
        "Feature Engineering",
        "Model Training",
        "Evaluation",
        "Inference",
      ],
      infrastructure: [
        "Docker",
        "CI/CD",
        "Cloud Deployment",
        "Monitoring",
      ],
    },
    impact: 45,
    impactLabel: "fraud detection improvement",
    summary: "Multi-model verification orchestrated in parallel — CNN + ViT + GAN + OCR via async FastAPI.",
    tags: ["Python", "FastAPI", "PyTorch", "PostgreSQL", "Redis", "Docker"],
    stackShort: ["Python", "FastAPI", "PyTorch"],
    url: "https://github.com/NYN-05/verisight",
    demoUrl: "https://github.com/NYN-05/verisight",
    status: "Production",
    featured: true,
    homepageFeatured: false,
    duration: "6 weeks",
    role: "Solo — Architecture, Backend, ML, Infrastructure",
  },
  {
    index: "05",
    slug: "scalable-ml-backend",
    image: "/assets/project-backend.png",
    title: "Distributed Task & Inference Backend",
    subtitle: "Scalable Asynchronous Microservice Infrastructure",
    category: "backend",
    categoryLabel: "Backend / Systems",
    categoryBadges: ["[BACKEND]", "[SYSTEMS]", "[REDIS]", "[DOCKER]", "[POSTGRESQL]"],
    desc: "Production backend microservice featuring asynchronous job queues, distributed Redis caching, connection pooling, and automated CI/CD pipeline deployments.",
    problem:
      "Heavy compute workloads bottlenecked web server threads, causing cascading request timeouts and high CPU spikes under concurrent user loads.",
    solution:
      "Decoupled request ingestion from processing using Redis task queues, worker pools with health monitoring, and response caching.",
    engineeringChallenges:
      "Graceful degradation during traffic bursts; cache invalidation across distributed instances; zero-downtime rolling container deployments.",
    impact: 60,
    impactLabel: "API latency reduction",
    summary: "Redis worker queues decoupling ingestion from heavy compute — 60% faster under load.",
    tags: ["FastAPI", "Redis", "Docker", "CI/CD", "PostgreSQL", "Python"],
    stackShort: ["FastAPI", "Redis", "Docker"],
    url: "https://github.com/NYN-05/verisight",
    demoUrl: "https://github.com/NYN-05/verisight",
    status: "Production",
    featured: true,
    homepageFeatured: false,
    duration: "4 weeks",
    role: "Solo — Architecture, Infrastructure, Backend",
  },
  {
    index: "06",
    slug: "preventive-movement-intelligence",
    image: "/assets/project-pmi.png",
    title: "Preventive Movement Intelligence",
    subtitle: "Real-Time Posture Analytics & Computer Vision Service",
    category: "software",
    categoryLabel: "Software / ML",
    categoryBadges: ["[SOFTWARE]", "[SYSTEMS]", "[COMPUTER VISION]", "[FASTAPI]"],
    desc: "Real-time posture analytics pipeline extracting multi-point pose coordinates and evaluating biomechanical joint kinematics at 30+ FPS.",
    problem:
      "Athletes and fitness practitioners lacked real-time, low-latency form feedback without expensive dedicated hardware.",
    solution:
      "Engineered a low-latency frame ingestion pipeline with confidence-based landmark filtering, biomechanical angle calculations, and dynamic risk scoring.",
    engineeringChallenges:
      "Fitting frame ingestion, landmark extraction, and kinetic scoring within a strict 33ms frame budget; handling camera occlusion gracefully.",
    impact: 72,
    impactLabel: "injury risk reduction",
    summary: "30+ FPS pose pipeline — landmark filtering + joint kinematics at 33ms frame budget.",
    tags: ["Python", "FastAPI", "TensorFlow", "MoveNet", "OpenCV", "AsyncIO"],
    stackShort: ["Python", "TensorFlow", "OpenCV"],
    url: "https://github.com/NYN-05/verisight",
    demoUrl: "https://github.com/NYN-05/verisight",
    status: "BIRAC Prototype",
    featured: true,
    homepageFeatured: false,
    duration: "5 weeks",
    role: "Solo — Research, Pipeline, API, Optimization",
  },
];