export const FEATURED_SLUGS = [
  "verisight",
  "scalable-ml-backend",
  "preventive-movement-intelligence",
];

export function getFeaturedProjects() {
  return FEATURED_SLUGS.map((slug) => PROJECTS.find((p) => p.slug === slug)).filter(Boolean);
}

export const PROJECTS = [
  {
    index: "01",
    slug: "verisight",
    image: "/assets/project-verisight.png",
    title: "VeriSight",
    subtitle: "Intelligent Image Authenticity Verification Platform",
    category: "ml-ai",
    categoryLabel: "ML / Backend",
    categoryBadges: ["[BACKEND]", "[SYSTEMS]", "[ML]", "[FASTAPI]", "[PYTORCH]"],
    desc: "An end-to-end intelligent system designed to solve high-volume digital tampering using a combination of backend engineering, asynchronous pipeline orchestration, and multi-model machine learning inference.",
    problem:
      "High-volume digital workflows lacked an automated, tamper-proof system to detect synthetic forgeries and metadata alterations under sub-second latency constraints.",
    solution:
      "Architected an asynchronous pipeline orchestrating deep learning models in parallel with strict timeout policies, confidence fusion, and structured audit logs.",
    engineeringChallenges:
      "Preventing head-of-line blocking during multi-model parallel inference; maintaining sub-500ms p95 latency under concurrent traffic; designing clean REST contracts with full auditability.",
    architecture: {
      flow: "Frontend (React) → API Gateway (FastAPI) → Application Layer (AsyncIO) → Database (PostgreSQL + Redis) → Parallel ML Inference (CNN + ViT + GAN + OCR)",
      engineeringCapabilities: [
        "REST APIs",
        "Authentication",
        "Database Design",
        "Async Processing",
        "Testing",
        "Deployment",
      ],
      mlCapabilities: [
        "Feature Engineering",
        "Model Training",
        "Evaluation",
        "Inference",
      ],
      infrastructure: [
        "Docker",
        "CI/CD",
        "Cloud Deployment",
        "Monitoring",
      ],
    },
    impact: 45,
    impactLabel: "fraud detection improvement",
    summary: "Multi-model verification orchestrated in parallel — CNN + ViT + GAN + OCR via async FastAPI.",
    tags: ["Python", "FastAPI", "PyTorch", "PostgreSQL", "Redis", "Docker"],
    stackShort: ["Python", "FastAPI", "PyTorch"],
    url: "https://github.com/NYN-05/verisight",
    demoUrl: "https://github.com/NYN-05/verisight",
    status: "Production",
    featured: true,
    homepageFeatured: true,
    duration: "6 weeks",
    role: "Solo — Architecture, Backend, ML, Infrastructure",
  },
  {
    index: "02",
    slug: "scalable-ml-backend",
    image: "/assets/project-backend.png",
    title: "Distributed Task & Inference Backend",
    subtitle: "Scalable Asynchronous Microservice Infrastructure",
    category: "backend",
    categoryLabel: "Backend / Systems",
    categoryBadges: ["[BACKEND]", "[SYSTEMS]", "[REDIS]", "[DOCKER]", "[POSTGRESQL]"],
    desc: "Production backend microservice featuring asynchronous job queues, distributed Redis caching, connection pooling, and automated CI/CD pipeline deployments.",
    problem:
      "Heavy compute workloads bottlenecked web server threads, causing cascading request timeouts and high CPU spikes under concurrent user loads.",
    solution:
      "Decoupled request ingestion from processing using Redis task queues, worker pools with health monitoring, and response caching.",
    engineeringChallenges:
      "Graceful degradation during traffic bursts; cache invalidation across distributed instances; zero-downtime rolling container deployments.",
    impact: 60,
    impactLabel: "API latency reduction",
    summary: "Redis worker queues decoupling ingestion from heavy compute — 60% faster under load.",
    tags: ["FastAPI", "Redis", "Docker", "CI/CD", "PostgreSQL", "Python"],
    stackShort: ["FastAPI", "Redis", "Docker"],
    url: "https://github.com/NYN-05/verisight",
    demoUrl: "https://github.com/NYN-05/verisight",
    status: "Production",
    featured: true,
    homepageFeatured: true,
    duration: "4 weeks",
    role: "Solo — Architecture, Infrastructure, Backend",
  },
  {
    index: "03",
    slug: "preventive-movement-intelligence",
    image: "/assets/project-pmi.png",
    title: "Preventive Movement Intelligence",
    subtitle: "Real-Time Posture Analytics & Computer Vision Service",
    category: "software",
    categoryLabel: "Software / ML",
    categoryBadges: ["[SOFTWARE]", "[SYSTEMS]", "[COMPUTER VISION]", "[FASTAPI]"],
    desc: "Real-time posture analytics pipeline extracting multi-point pose coordinates and evaluating biomechanical joint kinematics at 30+ FPS.",
    problem:
      "Athletes and fitness practitioners lacked real-time, low-latency form feedback without expensive dedicated hardware.",
    solution:
      "Engineered a low-latency frame ingestion pipeline with confidence-based landmark filtering, biomechanical angle calculations, and dynamic risk scoring.",
    engineeringChallenges:
      "Fitting frame ingestion, landmark extraction, and kinetic scoring within a strict 33ms frame budget; handling camera occlusion gracefully.",
    impact: 72,
    impactLabel: "injury risk reduction",
    summary: "30+ FPS pose pipeline — landmark filtering + joint kinematics at 33ms frame budget.",
    tags: ["Python", "FastAPI", "TensorFlow", "MoveNet", "OpenCV", "AsyncIO"],
    stackShort: ["Python", "TensorFlow", "OpenCV"],
    url: "https://github.com/NYN-05/verisight",
    demoUrl: "https://github.com/NYN-05/verisight",
    status: "BIRAC Prototype",
    featured: true,
    homepageFeatured: true,
    duration: "5 weeks",
    role: "Solo — Research, Pipeline, API, Optimization",
  },
  {
    index: "04",
    slug: "edushield",
    image: "/assets/project-edushield.png",
    title: "EduShield Security Platform",
    subtitle: "Phishing Email Detection & Threat Analysis Gateway",
    category: "software",
    categoryLabel: "Software / Security",
    categoryBadges: ["[SOFTWARE]", "[BACKEND]", "[NLP]", "[SCIKIT-LEARN]"],
    desc: "Real-time email security gateway combining text tokenization, heuristic feature extraction, and ensemble classification for suspicious email triage.",
    problem:
      "Educational institutions faced increasing credential harvesting attacks evading standard signature-based spam filters.",
    solution:
      "Constructed an automated email parsing service utilizing TF-IDF vectorization, calibrated classifiers, and explainable feature-attribution reports.",
    engineeringChallenges:
      "Minimizing false positives on legitimate administrative notices; implementing fast stream-based text parsing under sub-100ms response targets.",
    impact: 88,
    impactLabel: "detection accuracy",
    summary: "TF-IDF + calibrated classifiers with explainable token attribution — <100ms.",
    tags: ["Python", "scikit-learn", "FastAPI", "NLP", "TF-IDF", "SVM"],
    stackShort: ["Python", "scikit-learn", "FastAPI"],
    url: "https://github.com/NYN-05/verisight",
    demoUrl: "https://github.com/NYN-05/verisight",
    status: "Production",
    featured: false,
    homepageFeatured: false,
    duration: "4 weeks",
    role: "Solo — Pipeline, Model, REST API",
  },
  {
    index: "05",
    slug: "fullstack-analytics-dashboard",
    image: "/assets/project-verisight.png",
    title: "System Observability Hub",
    subtitle: "Real-Time Telemetry & Service Metrics Dashboard",
    category: "full-stack",
    categoryLabel: "Full Stack",
    categoryBadges: ["[FULL STACK]", "[REACT]", "[NODE.JS]", "[POSTGRESQL]"],
    desc: "Full-stack telemetry dashboard for monitoring service uptime, error budgets, database query latencies, and distributed system health metrics.",
    problem:
      "Distributed backend services generated isolated logs with no unified interface to visualize service degradation in real time.",
    solution:
      "Built a responsive React UI backed by Node.js/Express APIs, WebSocket telemetry streams, and aggregated PostgreSQL time-series tables.",
    engineeringChallenges:
      "Real-time WebSocket connection state management; efficient aggregation of high-frequency telemetry data without database contention.",
    impact: 99,
    impactLabel: "uptime visibility",
    summary: "WebSocket telemetry + PostgreSQL time-series — unified service health at a glance.",
    tags: ["React", "Node.js", "PostgreSQL", "Tailwind CSS", "WebSockets"],
    stackShort: ["React", "Node.js", "PostgreSQL"],
    url: "https://github.com/NYN-05/verisight",
    demoUrl: "https://github.com/NYN-05/verisight",
    status: "Production",
    featured: false,
    homepageFeatured: false,
    duration: "3 weeks",
    role: "Solo — Frontend, Backend API, Database Design",
  },
];